version: '3.8'

services:
  web:
    build :
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn House24.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/House24/web/static
      - media_volume:/home/House24/web/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/House24/web/static
      - media_volume:/home/House24/web/media
    ports:
      - "1337:80"
    depends_on:
      - web
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A House24 worker -l info
    volumes:
      - .:/home/House24/web/
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
