"""
Django settings for House24 project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get("SECRET_KEY")
SECRET_KEY = 'django-insecure-gd(e_xem_9mhj8h%mnvc37v!k6a^th&h8fp-w_oyq)z%gu&o0a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# CSRF_TRUSTED_ORIGINS = ['https://', 'http://','http://*', 'https://*']
CSRF_TRUSTED_ORIGINS = ['http://localhost:1337', 'http://localhost/*', 'http://localhost/',
                        'http://*', 'http://161.35.192.121:1337', 'http://161.35.192.1211337/*',
                        'http://161.35.192.121/',
                        'http://161.35.192.121/*', 'http://161.35.192.121/', 'http://161.35.192.121.13'
                        ]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'faceit.kawai@gmail.com'
EMAIL_HOST_PASSWORD = 'wbxl gubi ohjg jcsz'

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    "django_bootstrap5",
    'django.contrib.postgres',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_panel.apps.AdminPanelConfig',
    'users.apps.UsersConfig',
    'cabinet.apps.CabinetConfig',
    'website.apps.WebsiteConfig',
    "django_cleanup",
    'easy_thumbnails',
]
GOOGLE_RECAPTCHA_SECRET_KEY = '6LfR5ionAAAAAOBoMMJVwiwd-mp_6YJJtXEMD4Uj'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'House24.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cabinet.middlewares.user_info',

            ],
            'libraries': {
                'check_relation': 'admin_panel.templatetags.check_relation',
                'check_personal_account': 'admin_panel.templatetags.check_personal_account',
                'check_email': 'admin_panel.templatetags.check_email',
                'check_flat': 'admin_panel.templatetags.check_flat',
            }
        },
    },
]

WSGI_APPLICATION = 'House24.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "house24",
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),

        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # "NAME": os.environ.get("SQL_DATABASE"),
        # "USER": os.environ.get("SQL_USER"),
        # "PASSWORD": os.environ.get("SQL_PASSWORD"),
        # "HOST": os.environ.get("SQL_HOST"),
        # "PORT": os.environ.get("SQL_PORT"),

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "admin_panel.CustomUser"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LOGIN_URL = 'login'
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LOGIN_REDIRECT_URL = 'cabinet_statistic'
LOGOUT_REDIRECT_URL = 'main'
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True
USE_I10N = False

USE_TZ = True

DATE_FORMAT = '%m/%d/%Y'

THUMBNAIL_ALIASES = {
    '': {
        'main': {
            'size': (500, 300),
            'crop': 'scale',
        },
        '650-300': {
            'size': (650, 300),
            'crop': 'scale',
        },
        'house': {
            'size': (522, 350),
            'crop': 'scale',
        },
    },
}
THUMBNAIL_BASEDIR = 'thumbnails'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = []

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTHENTICATION_BACKENDS = ['users.authentication.EmailBackend']
